"""Build a single-file flograph script for environments where installing
the `flograph` package isn't an option (e.g. it's not yet approved on a
work package index).

The output is one .py file: the entire `src/flograph` tree, zipped and
base64-embedded, plus a small bootstrap that unpacks it to a temp dir,
puts that dir on sys.path, and launches the app. It does NOT bundle
third-party dependencies (PySide6, pandas, jedi, psutil) — those must
already be importable in whatever Python runs the script.

Usage:
    python scripts/build_onefile.py [output_path]

Default output: dist/flograph_onefile_<version>.py
"""
from __future__ import annotations

import base64
import io
import re
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src" / "flograph"
PYPROJECT = REPO_ROOT / "pyproject.toml"

EXCLUDE_DIR_NAMES = {"__pycache__"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo"}


def _read_version() -> str:
    text = PYPROJECT.read_text()
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    return match.group(1) if match else "0.0.0"


def _build_bundle_zip() -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(SRC_DIR.rglob("*")):
            if path.is_dir():
                continue
            if any(part in EXCLUDE_DIR_NAMES for part in path.parts):
                continue
            if path.suffix in EXCLUDE_SUFFIXES:
                continue
            arcname = "flograph/" + str(path.relative_to(SRC_DIR)).replace("\\", "/")
            zf.write(path, arcname)
    return buf.getvalue()


TEMPLATE = '''#!/usr/bin/env python3
"""flograph {version} — single-file bundle.

Generated by scripts/build_onefile.py — do not edit by hand.

Run with:  python flograph_onefile.py [project.flograph]

Requires PySide6, pandas, jedi, and psutil to already be importable in
whatever Python runs this file (see flograph's pyproject.toml for the
pinned minimum versions). This file does not install anything — it only
carries flograph's own source, so you can hand your Python environment
this one file instead of asking IT to approve a package install.
"""
from __future__ import annotations

import atexit
import base64
import io
import shutil
import sys
import tempfile
import zipfile

_BUNDLE_B64 = """
{bundle_b64}
"""


def _bootstrap() -> None:
    data = base64.b64decode(_BUNDLE_B64)
    tmp_dir = tempfile.mkdtemp(prefix="flograph_onefile_")
    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        zf.extractall(tmp_dir)
    sys.path.insert(0, tmp_dir)
    atexit.register(shutil.rmtree, tmp_dir, ignore_errors=True)


_bootstrap()

from flograph.app import main  # noqa: E402

if __name__ == "__main__":
    raise SystemExit(main())
'''


def build(output_path: Path) -> None:
    version = _read_version()
    bundle = _build_bundle_zip()
    bundle_b64 = base64.b64encode(bundle).decode("ascii")
    # wrap at 100 cols so the literal doesn't produce one giant line
    wrapped = "\n".join(bundle_b64[i:i + 100] for i in range(0, len(bundle_b64), 100))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(TEMPLATE.format(version=version, bundle_b64=wrapped))
    size_kb = output_path.stat().st_size / 1024
    print(f"wrote {output_path} ({size_kb:.0f} KiB, flograph {version})")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        out = Path(sys.argv[1])
    else:
        out = REPO_ROOT / "dist" / f"flograph_onefile_{_read_version()}.py"
    build(out)
